// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace YoYoCms.AbpProjectTemplate.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Tenancy_Filters_To_Abp_Zero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Tenancy_Filters_To_Abp_Zero));
        
        string IMigrationMetadata.Id
        {
            get { return "201503291617289_Added_Tenancy_Filters_To_Abp_Zero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
