// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace YoYoCms.AbpProjectTemplate.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserLogin_Property_Restrictions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserLogin_Property_Restrictions));
        
        string IMigrationMetadata.Id
        {
            get { return "201505011844158_UserLogin_Property_Restrictions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
