// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AuditLog_Made_MayHaveTenant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditLog_Made_MayHaveTenant));
        
        string IMigrationMetadata.Id
        {
            get { return "201506141245516_AuditLog_Made_MayHaveTenant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
