// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace YoYoCms.AbpProjectTemplate.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ModuleZero_Upgrade_For_ISuspendable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModuleZero_Upgrade_For_ISuspendable));
        
        string IMigrationMetadata.Id
        {
            get { return "201503011513570_ModuleZero_Upgrade_For_ISuspendable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
