// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace YoYoCms.AbpProjectTemplate.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AbpZero_Role_SoftDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AbpZero_Role_SoftDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201504051650417_AbpZero_Role_SoftDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
