// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Implemented_IMayHaveTenantId_For_UserOrganizationUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Implemented_IMayHaveTenantId_For_UserOrganizationUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201512100815485_Implemented_IMayHaveTenantId_For_UserOrganizationUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
