// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace YoYoCms.AbpProjectTemplate.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_AuditLog_To_AbpZero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_AuditLog_To_AbpZero));
        
        string IMigrationMetadata.Id
        {
            get { return "201503252020192_Added_AuditLog_To_AbpZero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
