// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_BackgroundJobs_And_Notifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_BackgroundJobs_And_Notifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201602021344016_Added_BackgroundJobs_And_Notifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
