// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ABP_Notification_Revisions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ABP_Notification_Revisions));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051543169_ABP_Notification_Revisions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
