// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_LinkUserId_To_AbpUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_LinkUserId_To_AbpUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201602020753064_Added_LinkUserId_To_AbpUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
