// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Make_FriendShip_And_Chat_TenantId_Nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_FriendShip_And_Chat_TenantId_Nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606161233356_Make_FriendShip_And_Chat_TenantId_Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
