// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Notification_And_Setting_Changes_For_DbPerTenant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notification_And_Setting_Changes_For_DbPerTenant));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221405375_Notification_And_Setting_Changes_For_DbPerTenant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
