// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Module_Zero_v1_Improvements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Module_Zero_v1_Improvements));
        
        string IMigrationMetadata.Id
        {
            get { return "201609221300383_Module_Zero_v1_Improvements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
