// <auto-generated />
namespace YoYoCms.AbpProjectTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_MayHaveTenant_Annotation_To_ChatMessage_And_Friendship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MayHaveTenant_Annotation_To_ChatMessage_And_Friendship));
        
        string IMigrationMetadata.Id
        {
            get { return "201606240745029_Add_MayHaveTenant_Annotation_To_ChatMessage_And_Friendship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
